# Generated by Django 3.2.13 on 2022-05-15 16:22

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('get2sail_app', '0004_rename_user_location_user_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='location',
            unique_together={('id', 'user_id')},
        ),
        migrations.AlterIndexTogether(
            name='location',
            index_together={('id', 'user_id')},
        ),
    ]
