# Generated by Django 3.2.13 on 2022-05-23 09:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('get2sail_app', '0005_auto_20220515_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='location',
            unique_together=set(),
        ),
        migrations.AlterIndexTogether(
            name='location',
            index_together=set(),
        ),
        migrations.RemoveField(
            model_name='location',
            name='uname',
        ),
    ]
