# Generated by Django 3.2.13 on 2022-05-23 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('get2sail_app', '0006_auto_20220523_0951'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='user_id',
            new_name='uid',
        ),
    ]
